### ISSUE TITLE
Docker install whith no errors but doesn´t working properly

### ISSUE THREAD

**Issue by cesarPano** [ToolJet/ToolJet#3941]
Hi.
I have tried docker install local and it works properly. But when installing it on a time4vps cloud machine it doesn´t work.
After diving in previous issues with similar problems, I haven´t found the solution to my problem.
Maybe I am forgetting something, but once I have tried changing IPs, urls, ... I don´t know what else I can do.
Any idea about this?
Thanks in advance.

### Environment
    Docker / Linux Ubuntu 20.04

### What is the expected behaviour?
  I expect Tooljet to run over docker on a time4VPS cloud machine

### What is the current behaviour?
  After following all the steps, everything appears to run properly, but I get nothing in the browser

### How to reproduce the issue?

1. Get a time4vps machine (linux 4GB)
2. Follow steps in https://docs.tooljet.com/docs/setup/docker
3. Go to the browser and get ... nothing, but an error on the console

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/65397642/188096488-c4f37796-a818-4564-9693-86c5379a15ec.png)
![image](https://user-images.githubusercontent.com/65397642/188096712-31e69fdb-37c9-469a-8144-13bab495b8aa.png)

### Please provide any traces or logs that could help here.

------------------ cat .env
TOOLJET_HOST=https://46q5.l.time4vps.cloud
LOCKBOX_MASTER_KEY=xxxxxxxxx
SECRET_KEY_BASE=xxxxxxxxxxxxxxxxxx
ORM_LOGGING=all
PG_DB=tooljet_production
PG_USER=postgres
PG_HOST=postgres
PG_PASS=postgres
CHECK_FOR_UPDATES=0
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
DEFAULT_FROM_EMAIL=hello@tooljet.io
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_DOMAIN=
SMTP_PORT=
DISABLE_SIGNUPS=
APM_VENDOR=
SENTRY_DNS=
SENTRY_DEBUG=
COMMENT_FEATURE_ENABLE=
ENABLE_MULTIPLAYER_EDITING=true
SSO_DISABLE_SIGNUP=
SSO_RESTRICTED_DOMAIN=
SSO_GOOGLE_OAUTH2_CLIENT_ID=
SSO_GIT_OAUTH2_CLIENT_ID=
SSO_GIT_OAUTH2_CLIENT_SECRET=
SSO_GIT_OAUTH2_HOST=
DEPLOYMENT_PLATFORM=docker

----------- docker-compose.yaml
version: '3'

services:
  client:
    tty: true
    stdin_open: true
    image: tooljet/tooljet-client-ce:latest
    restart: always
    env_file: .env
    depends_on:
      - server
    volumes:
      - logs:/var/log/openresty/
      - certs:/etc/resty-auto-ssl/
      - fallbackcerts:/etc/fallback-certs
    ports:
      - 80:80
      - 443:443
    command: openresty -g "daemon off;"

  server:
    image: tooljet/tooljet-server-ce:latest
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 3000
    env_file: .env
    environment:
      SERVE_CLIENT: "false"
    command: npm run start:prod
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/postgres_data
  certs:
  logs:
  fallbackcerts:

**Comment by shivangT** [comment]
Hey @cesarPano 
We’ll look into this and get back soon. Kindly join our slack channel to get your queries resolved quicker. 
Thanks

**Comment by gsdiniz** [comment]
This problem occurs in versions (tooljet/tooljet-server-ce/tooljet/tooljet-client-ce):

latest
1.24.*
1.23.*

a stable version I've found is 1.22.*

**Comment by cesarPano** [comment]
Thanks a lot. It is already working... (1.22.4)

**Comment by SDBdevelopment** [comment]
After upgrading from 1.22.* to 1.23.* or 1.24.* ToolJet is still working. But when you force a refresh (Ctrl-F5) of any page 1.23.* and 1.24.* are no longer working. Hope this info helps with finding the problem.

**Comment by shivangT** [comment]
Hey @SDBdevelopment 
Thank you for the information. We’ll look into it and get back here.

**Comment by AdamHghs** [comment]
I have tried v1.22.4 and latest run into the blank page issue when going to the domain name. if I go to the IP the login page shows up correctly. (I have tried both my IP and the FQDN set as the TOOLJET_HOST variable).

Additionally

The command to seed the database doesn't run
docker-compose run server npm run db:seed

```> tooljet@1.18.0 db:seed /app
> npm --prefix server run db:seed


> server@0.0.1 db:seed /app/server
> ts-node -r tsconfig-paths/register --transpile-only ./scripts/seeds.ts

Couldn't find tsconfig.json. tsconfig-paths will be skipped
Error: Cannot find module '../src/app.module'
Require stack:
- /app/server/scripts/seeds.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/app/server/scripts/seeds.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/app/server/node_modules/ts-node/src/index.ts:1295:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/app/server/node_modules/ts-node/src/index.ts:1298:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@0.0.1 db:seed: `ts-node -r tsconfig-paths/register --transpile-only ./scripts/seeds.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the server@0.0.1 db:seed script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-05T01_45_37_569Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tooljet@1.18.0 db:seed: `npm --prefix server run db:seed`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tooljet@1.18.0 db:seed script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-05T01_45_37_608Z-debug.log

**Comment by gsdiniz** [comment]
> OS: Ubuntu 22.04 Docker Engine: 20.10.17
> 
> I have tried v1.22.4 and latest run into the blank page issue when going to the domain name. if I go to the IP the login page shows up correctly. (I have tried both my IP and the FQDN set as the TOOLJET_HOST variable).
> 
> Additionally
> 
> The command to seed the database doesn't run docker-compose run server npm run db:seed
> 
> ```
> > npm --prefix server run db:seed
> 
> 
> > server@0.0.1 db:seed /app/server
> > ts-node -r tsconfig-paths/register --transpile-only ./scripts/seeds.ts
> 
> Couldn't find tsconfig.json. tsconfig-paths will be skipped
> Error: Cannot find module '../src/app.module'
> Require stack:
> - /app/server/scripts/seeds.ts
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
>     at Module.require (internal/modules/cjs/loader.js:974:19)
>     at require (internal/modules/cjs/helpers.js:92:18)
>     at Object.<anonymous> (/app/server/scripts/seeds.ts:2:1)
>     at Module._compile (internal/modules/cjs/loader.js:1085:14)
>     at Module.m._compile (/app/server/node_modules/ts-node/src/index.ts:1295:23)
>     at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
>     at Object.require.extensions.<computed> [as .ts] (/app/server/node_modules/ts-node/src/index.ts:1298:12)
>     at Module.load (internal/modules/cjs/loader.js:950:32)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! server@0.0.1 db:seed: `ts-node -r tsconfig-paths/register --transpile-only ./scripts/seeds.ts`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the server@0.0.1 db:seed script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2022-09-05T01_45_37_569Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! tooljet@1.18.0 db:seed: `npm --prefix server run db:seed`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the tooljet@1.18.0 db:seed script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2022-09-05T01_45_37_608Z-debug.log
> ```

You must run db:seed:prod

**Comment by akshaysasidrn** [comment]
We have fixed the issue. Please make of use `v1.24.2`. 
You can find the updated docs [here](https://docs.tooljet.com/docs/setup/docker).
